spring.application.name=state-ledger

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/state_ledger_db
spring.datasource.username=postgres
spring.datasource.password=Armaan@2006
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true